---
permalink: sm-storage/application-specific-workloads.html 
sidebar: sidebar 
keywords: workload, storage, object, support, application, define, instance, application, system manager, configure, contain, volume, similar, underlying, characteristics, optimized, type, microsoft server, subsequent 
summary: 工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序， System Manager 会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。 
---
= 应用程序特定的工作负载
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序， System Manager 会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

在创建卷期间、System Manager会提示您回答有关工作负载使用情况的问题解答 问题。例如、如果要为Microsoft Exchange创建卷、系统会询问您需要多少邮箱、平均邮箱容量要求是多少以及所需数据库副本的数量。System Manager可使用此信息为您创建最佳卷配置、并可根据需要对其进行编辑。或者、您也可以在卷创建序列中跳过此步骤。



== 工作负载类型

您可以创建两种类型的工作负载：特定于应用程序的工作负载和其他工作负载。

* *特定于应用程序*。在使用应用程序特定的工作负载创建卷时、系统可能会建议优化卷配置、以最大程度地减少应用程序工作负载I/O与应用程序实例中的其他流量之间的争用。对于为以下应用程序类型创建的工作负载、系统会自动建议并优化卷特征、例如I/O类型、区块大小、控制器所有权以及读写缓存。
+
** Microsoft®SQL Server (Microsoft®SQL Server)
** Microsoft®Exchange Server (Microsoft®Exchange Server)
** 视频监控应用程序
** VMware ESXi®(适用于要与虚拟机文件系统结合使用的卷)
+
您可以使用*添加/编辑卷*对话框查看建议的卷配置以及编辑、添加或删除系统建议的卷和特征。



* *其他*(或不支持特定卷创建的应用程序)。其他工作负载使用的卷配置、如果您要创建的工作负载不与特定应用程序关联、或者System Manager没有为要在存储阵列上使用的应用程序进行内置优化、则必须手动指定。必须使用*添加/编辑卷*对话框手动指定卷配置。




== 应用程序和工作负载视图

您可以通过以下几种不同方式查看与应用程序特定工作负载关联的信息：

* 您可以选择*卷*图块中的*应用程序和工作负载*选项卡、以查看按工作负载分组的存储阵列卷以及与工作负载关联的应用程序类型。
* 您可以选择*性能*图块中的*应用程序和工作负载*选项卡、以查看逻辑对象的性能指标(延迟、IOPS和MBs)。对象按应用程序和关联工作负载分组。通过定期收集此性能数据、您可以建立基线测量并分析趋势、这有助于您调查与I/O性能相关的问题。

