---
permalink: sm-storage/create-pool-manually.html 
sidebar: sidebar 
keywords: create, pool, manually, set, candidates, auto configuration, feature, provide, meet, needs, logical, storage, capacity, necessary, individual, volumes, use, host, application 
summary: 如果池自动配置功能不提供满足您需求的池、您可以从一组候选对象手动创建池。池可提供必要的逻辑存储容量、您可以从中创建各个卷、然后使用这些卷托管应用程序。 
---
= 手动创建池
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果池自动配置功能不提供满足您需求的池、您可以从一组候选对象手动创建池。池可提供必要的逻辑存储容量、您可以从中创建各个卷、然后使用这些卷托管应用程序。

.开始之前
* 必须至少有11个驱动器具有相同的驱动器类型(HDD或SSD)。
* 磁盘架丢失保护要求构成池的驱动器至少位于六个不同的驱动器架中、并且一个驱动器架中的驱动器不超过两个。
* 抽盒丢失保护功能要求构成池的驱动器至少位于五个不同的抽盒中、并且池中每个抽盒包含同等数量的驱动器架。
* 配置EF600存储阵列时、请确保每个控制器都可以访问前12个插槽中相同数量的驱动器、以及最后12个插槽中相同数量的驱动器。此配置有助于控制器更有效地使用驱动器端PCIe总线。目前、System Manager允许在创建卷组时在"高级"功能下选择驱动器。要创建池、建议使用存储阵列中的所有驱动器。


.步骤
. 选择菜单：Storage[Pools & Volume Groups]。
. 单击菜单：创建[池]。
+
此时将显示*创建池*对话框。

. 键入池的名称。
. *可选：*如果存储阵列中有多种类型的驱动器、请选择要使用的驱动器类型。
+
结果表列出了您可以创建的所有可能池。

. 根据以下特征选择要使用的候选池、然后单击*创建*。


[cols="2*"]
|===
| 特性 | 使用 ... 


 a| 
可用容量
 a| 
以GiB显示候选池的可用容量。选择一个具有满足应用程序存储需求的容量的候选池。

保留(备用)容量也会分布在整个池中、而不是可用容量的一部分。



 a| 
驱动器总数
 a| 
显示候选池中的可用驱动器数量。

System Manager会自动预留尽可能多的驱动器以保留容量(对于池中的每六个驱动器、System Manager会为保留容量预留一个驱动器)。

发生驱动器故障时、会使用保留容量来保存重建的数据。



 a| 
支持安全保护
 a| 
指示候选池是否全部由具有安全功能的驱动器组成、这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。

* 您可以使用驱动器安全保护池、但所有驱动器都必须具有安全功能才能使用此功能。
* 如果要创建仅FDE池、请在安全功能列中查找*是- FDE*。如果要创建纯FIPS池、请在支持安全列中查找*是- FIPS *。
* 您可以创建一个由驱动器组成的池、这些驱动器可能支持安全功能、也可能不支持安全功能、或者混合了多种安全级别。如果池中的驱动器包含不支持安全的驱动器、则无法确保池的安全。




 a| 
是否启用安全性？
 a| 
提供了使用支持安全的驱动器启用驱动器安全功能的选项。如果池支持安全、并且您已创建安全密钥、则可以选中复选框来启用安全性。

[NOTE]
====
启用驱动器安全性后删除驱动器安全性的唯一方法是删除池并擦除驱动器。

====


 a| 
支持DA
 a| 
指示此池候选项是否可使用数据保证(Data Assurance、DA)。DA可检查并更正在数据通过控制器向下传输到驱动器时可能发生的错误。

如果要使用DA、请选择一个支持DA的池。只有在启用了DA功能后、此选项才可用。

池可以包含支持DA或不支持DA的驱动器、但要使用此功能、所有驱动器都必须支持DA。



 a| 
磁盘架丢失保护
 a| 
显示磁盘架丢失保护是否可用。

磁盘架丢失保护功能可确保在与单个驱动器磁盘架完全失去通信时能够访问池中卷上的数据。



 a| 
抽盒丢失保护
 a| 
显示是否提供了抽盒丢失保护、只有在使用包含抽盒的驱动器架时、才会提供此保护。

抽盒丢失保护功能可确保在与驱动器架中的单个抽盒完全失去通信时能够访问池中卷上的数据。

|===