---
permalink: sm-storage/functional-comparison-of-pools-and-volume-groups.html 
sidebar: sidebar 
keywords: function, purpose, pool, volume, group, same, objects, set, drives, logically, together, storage, array, create, host, access 
summary: 池和卷组的功能和用途相同。这两个对象都是一组驱动器、这些驱动器在存储阵列中逻辑分组在一起、用于创建主机可以访问的卷。 
---
= 池和卷组的功能比较
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
池和卷组的功能和用途相同。这两个对象都是一组驱动器、这些驱动器在存储阵列中逻辑分组在一起、用于创建主机可以访问的卷。

下表可帮助您确定池或卷组是否最适合您的存储需求。

[cols="3*""]
|===
| 功能 | 池 | 卷组 


 a| 
支持不同的RAID级别
 a| 
否始终为RAID 6。
 a| 
是的。RAID 0、1、10、5和6可用。



 a| 
支持的精简卷
 a| 
是的。
 a| 
否



 a| 
支持全磁盘加密(FDE)
 a| 
是的。
 a| 
是的。



 a| 
支持数据保证(Data Assurance、DA)
 a| 
是的。
 a| 
是的。



 a| 
支持磁盘架丢失保护
 a| 
是的。
 a| 
是的。



 a| 
支持抽盒丢失保护
 a| 
是的。
 a| 
是的。



 a| 
支持混合驱动器速度
 a| 
建议相同、但不是必需的。最慢的驱动器决定了所有驱动器的速度。
 a| 
建议相同、但不是必需的。最慢的驱动器决定了所有驱动器的速度。



 a| 
支持混合驱动器容量
 a| 
建议相同、但不是必需的。最小驱动器决定了所有驱动器的容量。
 a| 
建议相同、但不是必需的。最小驱动器决定了所有驱动器的容量。



 a| 
最小驱动器数
 a| 
11.
 a| 
取决于RAID级别。RAID 0需要1。RAID 1或10需要2 (需要偶数)。RAID 5最小值为3。RAID 6最小值为5。



 a| 
最大驱动器数
 a| 
最高可达存储阵列的最大限制
 a| 
RAID 1和10—最多达到存储阵列RAID 5的最大限制、6-30个驱动器



 a| 
可以在创建卷时选择单个驱动器
 a| 
否
 a| 
是的。



 a| 
可以在创建卷时指定分段大小
 a| 
是的。支持128 K。
 a| 
是的。



 a| 
可以在创建卷时指定I/O特征
 a| 
否
 a| 
是的。支持文件系统、数据库、多媒体和自定义。



 a| 
驱动器故障保护
 a| 
在池中的每个驱动器上使用保留容量、从而加快重建速度。
 a| 
使用热备用驱动器。重建受驱动器IOPS的限制。



 a| 
达到容量限制时显示警告
 a| 
是的。可以在已用容量达到最大容量的百分比时设置警报。
 a| 
否



 a| 
支持迁移到其他存储阵列
 a| 
否要求您先迁移到卷组。
 a| 
是的。



 a| 
动态区块大小(DSS)
 a| 
否
 a| 
是的。



 a| 
可以更改RAID级别
 a| 
否
 a| 
是的。



 a| 
卷扩展(增加容量)
 a| 
是的。
 a| 
是的。



 a| 
容量扩展(添加容量)
 a| 
是的。
 a| 
是的。



 a| 
容量减少
 a| 
是的。
 a| 
否

|===
[NOTE]
====
池或卷组均不支持混合驱动器类型(HDD、SSD)。

====