---
settings:
  name: SANtricity 11.6
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '11.6'
    url: "/e-series-santricity-116"
  - version-number: '11.8'
    url: "/e-series-santricity"
  - version-number: '11.7'
    url: "/e-series-santricity-117"
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: SANtricity 11.6文档
    url: "/index.html"
  - title: System Manager
    entries:
    - section: sm-interface
    - section: sm-storage
    - section: sm-mirroring
    - section: sm-hardware
    - section: sm-settings
    - section: sm-support
  - title: Unified Manager
    entries:
    - section: um-admin
    - section: um-manage
    - section: um-certificates
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
