---
permalink: sm-hardware/controller-terminology.html 
sidebar: sidebar 
keywords: controller, terms, storage, array 
summary: 了解控制器术语如何应用于存储阵列。 
---
= 控制器术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解控制器术语如何应用于存储阵列。

[cols="1a,3a"]
|===
| 组件 | Description 


 a| 
控制器
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实施 System Manager 功能。



 a| 
控制器架
 a| 
控制器架包含一组驱动器和一个或多个控制器箱。控制器箱用于存放控制器、主机接口卡(Host Interface Card、HIC)和电池。



 a| 
DHCP
 a| 
动态主机配置协议(DHCP)是Internet协议(IP)网络上使用的一种协议、用于动态分布网络配置参数、例如IP地址。



 a| 
DNS
 a| 
域名系统(Domain Name System、DNS)是一种命名系统、用于命名连接到Internet或专用网络的设备。DNS服务器维护一个域名目录、并将其转换为Internet协议(IP)地址。



 a| 
双工配置
 a| 
双工是存储阵列中的双控制器模块配置。双工系统在控制器、逻辑卷路径和磁盘路径方面是完全冗余的。如果一个控制器发生故障、另一个控制器将接管其I/O以保持可用性。双工系统还具有冗余风扇和电源。



 a| 
全双工/半双工连接
 a| 
全双工和半双工是指连接模式。在全双工模式下、两个设备可以同时双向通信。在半双工模式下、设备可以一次单向通信(一个设备发送消息、而另一个设备接收消息)。



 a| 
HIC
 a| 
可以选择将主机接口卡（ HIC ）安装在控制器箱中。控制器中内置的主机端口称为基板主机端口。HIC 中内置的主机端口称为 HIC 端口。



 a| 
ICMP ping响应
 a| 
Internet控制消息协议(Internet Control Message Protocol、ICMP)是网络计算机的操作系统用来发送消息的协议。ICMP消息可确定主机是否可访问以及从该主机获取数据包所需的时间。



 a| 
MAC 地址
 a| 
以太网使用介质访问控制标识符(MAC地址)来区分连接同一物理传输网络接口上两个端口的不同逻辑通道。



 a| 
管理客户端
 a| 
管理客户端是指安装了浏览器以访问System Manager的计算机。



 a| 
MTU
 a| 
最大传输单元(Maximum Transmission Unit、MTU)是可在网络中发送的最大数据包或帧。



 a| 
NTP
 a| 
网络时间协议(NTP)是一种网络协议、用于在数据网络中的计算机系统之间进行时钟同步。



 a| 
单工配置
 a| 
单工是存储阵列中的单控制器模块配置。单工系统不提供控制器或磁盘路径冗余、但具有冗余风扇和电源。



 a| 
VLAN
 a| 
虚拟局域网(VLAN)是一种逻辑网络、其行为与相同设备(交换机、路由器等)支持的其他网络在物理上是分开的。

|===