---
permalink: sm-hardware/drive-terminology.html 
sidebar: sidebar 
keywords: drive, apply, storage array 
summary: 了解驱动器术语如何应用于存储阵列。 
---
= 驱动器术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解驱动器术语如何应用于存储阵列。

[cols="1a,3a"]
|===
| 组件 | Description 


 a| 
da.
 a| 
数据保证(Data Assurance、DA)是一项功能、用于检查并更正在数据通过控制器向下传输到驱动器时可能发生的错误。可以在池或卷组级别启用数据保证、主机使用光纤通道等具有DA功能的I/O接口。



 a| 
驱动器安全功能
 a| 
驱动器安全性是一种存储阵列功能，可通过全磁盘加密（ Full Disk Encryption ， FDE ）驱动器或联邦信息处理标准（ Federal Information Processing Standard ， FIPS ）驱动器提供额外的安全层。如果将这些驱动器与驱动器安全功能结合使用，则需要使用安全密钥才能访问其数据。从阵列中物理删除驱动器后、这些驱动器将无法运行、直到将其安装到另一个阵列中为止、此时、这些驱动器将处于安全锁定状态、直到提供了正确的安全密钥为止。



 a| 
驱动器架
 a| 
驱动器架也称为扩展架、其中包含一组驱动器和两个输入/输出模块(IOM)。IOM包含SAS端口、用于将驱动器架连接到控制器架或其他驱动器架。



 a| 
DULBE
 a| 
已取消分配或未写入逻辑块错误(DULBE")是NVMe驱动器上的一个选项、它允许存储阵列取消分配卷中的块。取消分配驱动器上的块可以显著缩短初始化卷所需的时间。此外、主机还可以使用NVMe Dataset Management命令取消分配卷中的逻辑块。



 a| 
FDE驱动器
 a| 
全磁盘加密(Full Disk Encryption、FDE)驱动器在硬件级别对磁盘驱动器执行加密。硬盘驱动器包含一个ASIC芯片、用于在写入期间对数据进行加密、然后在读取期间对数据进行解密。



 a| 
FIPS驱动器
 a| 
FIPS驱动器使用联邦信息处理标准(FIPS) 140-2级别2。它们本质上是FDE驱动器、符合美国政府标准、可确保强大的加密算法和方法。FIPS驱动器的安全标准高于FDE驱动器。



 a| 
HDD
 a| 
硬盘驱动器（ HDD ）是指使用带有磁性层的旋转金属盘的数据存储设备。



 a| 
热备用驱动器
 a| 
热备用磁盘在RAID 1、RAID 5或RAID 6卷组中充当备用驱动器。它们是功能完备的驱动器、不包含任何数据。如果卷组中的驱动器发生故障、控制器会自动将故障驱动器中的数据重新构建为热备用磁盘。



 a| 
NVMe
 a| 
Non-Volatile Memory Express (NVMe)是一种专为SSD驱动器等基于闪存的存储设备设计的接口。与以前的逻辑设备接口相比、NVMe可降低I/O开销并提高性能。



 a| 
（ SAS ）。
 a| 
串行连接 SCSI （ SAS ）是一种点对点串行协议，可将控制器直接链接到磁盘驱动器。



 a| 
支持安全的驱动器
 a| 
支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器、这些驱动器可在写入期间对数据进行加密、并在读取期间对数据进行解密。这些驱动器被视为安全驱动器-_capable"、因为可以使用驱动器安全功能提高安全性。如果为这些驱动器使用的卷组和池启用了驱动器安全功能、则这些驱动器将变为secure—_enabled_.



 a| 
已启用安全保护的驱动器
 a| 
启用了安全保护的驱动器与驱动器安全功能结合使用。启用驱动器安全功能后、如果将驱动器安全应用于安全-_capable"驱动器上的池或卷组、则这些驱动器将变为安全_-enabled__。只能通过配置了正确安全密钥的控制器进行读写访问。这种增强的安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。



 a| 
SSD
 a| 
固态磁盘（ SSD ）是指使用固态内存（ Flash ）持久存储数据的数据存储设备。SSD 可模拟传统硬盘驱动器，并可与硬盘驱动器使用相同的接口。

|===