---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: erase, secure, enabled, drive, reuse, volume, group, pool, ssd cache, storage array 
summary: 您可以擦除启用了安全保护的驱动器、以便可以在其他卷组、池、SSD缓存或存储阵列中重复使用。此操作步骤 会重置驱动器的安全属性、并确保无法再次读取数据。 
---
= 擦除已启用安全保护的驱动器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以擦除启用了安全保护的驱动器、以便可以在其他卷组、池、SSD缓存或存储阵列中重复使用。此操作步骤 会重置驱动器的安全属性、并确保无法再次读取数据。

启用了安全保护的驱动器必须处于未分配状态。

只有在要删除启用了安全的驱动器上的所有数据并重置驱动器的安全属性时、才使用安全擦除选项。

[CAUTION]
====
*可能的数据丢失*-无法撤消安全擦除操作。确保在操作步骤 期间选择正确的驱动器。

====
.步骤
. 选择 * 硬件 * 。
. 如果图形显示了控制器、请单击*显示磁盘架正面*。
+
此图将发生变化、以显示驱动器、而不是控制器。

. 使用筛选器字段可查看磁盘架中所有已启用安全保护的未分配驱动器。从*显示驱动器...*下拉列表中、选择*安全启用*和*未分配*。
+
[NOTE]
====
如果所有驱动器共享相同的物理属性、则不会显示*显示驱动器...*筛选字段。如果所有驱动器共享相同的逻辑属性、则不会显示存储阵列*筛选器字段中的*任意位置。

磁盘架视图仅显示已启用安全保护的未分配驱动器；所有其他驱动器均显示为灰色。

====
. 选择要擦除的已启用安全保护的驱动器。
+
[CAUTION]
====
*可能的数据丢失*—确保选择的驱动器正确无误。完成安全擦除操作后、您将无法恢复任何数据。

====
+
此时将打开驱动器的上下文菜单。

. 选择*安全擦除*。
+
只有在选择已启用安全保护的未分配驱动器时、才会显示安全擦除选项。

+
[NOTE]
====
对于NVMe SED驱动器、您必须提供PSID。您可以在驱动器标签上找到PSID。如果没有备份锁定密钥、则必须执行此操作。

====
. 在安全擦除驱动器对话框中、阅读有关数据丢失的重要信息。
. 确认此操作、然后单击*擦除*。


现在、该驱动器可在另一个卷组或磁盘池中使用、也可在另一个存储阵列中使用。
