---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: configuration, snmp alerts, identification, one server, storage array, snmp traps, community name, ip address 
summary: '要配置简单网络管理协议(Simple Network Management Protocol、SNMP)警报、您必须至少确定一台存储阵列的事件监控器可以发送SNMP陷阱的服务器。此配置需要服务器的社区名称和IP地址。' 
---
= 配置SNMP警报的社区和目标
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要配置简单网络管理协议(Simple Network Management Protocol、SNMP)警报、您必须至少确定一台存储阵列的事件监控器可以发送SNMP陷阱的服务器。此配置需要服务器的社区名称和IP地址。

.开始之前
* 必须为网络服务器配置SNMP服务应用程序。您需要此服务器的网络地址(IPv4或IPv6地址)、以便事件监控器可以向该地址发送陷阱消息。您可以使用多个服务器(最多允许10个服务器)。
* 必须创建一个社区名称、该名称仅包含可打印的ASCII字符。社区名称是一个类似于网络服务器密码的字符串、通常由网络管理员创建。最多可以创建256个社区。
* 已使用SNMP服务应用程序在服务器上复制和编译管理信息库(Management Information Base、MIB)文件。此MIB文件定义了要监控和管理的数据。
+
如果您没有MIB文件、可以从NetApp支持站点获取：

+
** 转至 https://mysupport.netapp.com/site/["NetApp 支持"^]。
** 单击*下载*。
** 单击*软件*。
** 找到您的管理软件(例如SANtricity 系统管理器)、然后单击右侧的*执行！*。
** 单击最新版本上的"*查看并下载"*。
** 单击页面底部的*继续*。
** 接受 EULA 。
** 向下滚动、直到看到SNMP陷阱的* MIB文件*、然后单击链接下载此文件。




.关于此任务
此任务介绍如何识别陷阱目标的SNMP服务器、然后测试您的配置。

.步骤
. 选择*菜单：设置[警报]*。
. 选择* SNMP *选项卡。
+
如果尚未配置社区、则SNMP选项卡会显示"Configure Community"。

. 选择*配置社区*。
+
此时将打开*配置社区*对话框。

. 在*社区名称*字段中、输入网络服务器的一个或多个社区字符串、然后单击*保存*。
+
"警报"页面将显示"添加陷阱目标"。

. 选择*添加陷阱目标*。
+
此时将打开*添加陷阱目标*对话框。

. 输入一个或多个陷阱目标、选择其关联的社区名称、然后单击*添加*。
+
** *陷阱目标*-输入运行SNMP服务的服务器的IPv4或IPv6地址。
** *社区名称*-从下拉列表中、选择此陷阱目标的社区名称。(如果您仅定义了一个社区名称、则此名称已显示在此字段中。)
** *发送身份验证失败陷阱*-如果要在SNMP请求因团体名称无法识别而被拒绝时向陷阱目标发出警报、请选择此选项(复选框)。单击*添加*后、陷阱目标和关联的社区名称将显示在*警报*页面的* SNMP*选项卡中。


. 要确保陷阱有效、请从表中选择一个陷阱目标、然后单击*测试陷阱目标*向配置的地址发送测试陷阱。


.结果
每当发生可更改的事件时、事件监控器都会向服务器发送SNMP陷阱。
