---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: secure, enable, storage array, appropriate, importing, new storage, drive 
summary: 如果要将启用了安全保护的驱动器从一个存储阵列移动到另一个存储阵列、则必须将相应的安全密钥导入到新存储阵列中。导入密钥会解锁驱动器上的数据。 
---
= 使用安全密钥解锁驱动器
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要将启用了安全保护的驱动器从一个存储阵列移动到另一个存储阵列、则必须将相应的安全密钥导入到新存储阵列中。导入密钥会解锁驱动器上的数据。

.开始之前
* 目标存储阵列(要移动驱动器的存储阵列)必须已配置安全密钥。迁移的驱动器将重新密钥设置到目标存储阵列。
* 您必须知道与要解锁的驱动器关联的安全密钥。
* 管理客户端(具有用于访问System Manager的浏览器的系统)上提供了安全密钥文件。如果要将驱动器移动到由其他系统管理的存储阵列、则需要将安全密钥文件移动到该管理客户端。


此任务介绍如何解锁已从存储阵列中删除并重新安装在另一个存储阵列中的已启用安全的驱动器中的数据。阵列发现驱动器后、将显示"需要注意"情况、并为这些重新定位的驱动器显示"需要安全密钥"状态。您可以通过将驱动器数据的安全密钥导入到存储阵列中来解锁驱动器数据。在此过程中、您可以选择安全密钥文件并输入密钥的密码短语。

[NOTE]
====
密码短语与存储阵列的管理员密码不同。

====
如果新存储阵列中安装了其他启用了安全保护的驱动器、则这些驱动器使用的安全密钥可能与您要导入的安全密钥不同。在导入过程中、旧安全密钥仅用于解锁要安装的驱动器的数据。成功完成解锁过程后、新安装的驱动器将重新密钥到目标存储阵列的安全密钥。

.步骤
. 选择菜单：设置[系统]。
. 在*安全密钥管理*下、选择*解锁安全驱动器*。
+
此时将打开解除安全驱动器锁定对话框。表中显示了需要安全密钥的所有驱动器。

. *可选：*将鼠标悬停在驱动器编号上方可查看驱动器的位置(磁盘架编号和托架编号)。
. 单击*浏览*、然后选择与要解锁的驱动器对应的安全密钥文件。
+
您选择的密钥文件将显示在对话框中。

. 输入与此密钥文件关联的密码短语。
+
输入的字符将被屏蔽。

. 单击*解锁*。
+
如果解锁操作成功、则对话框将显示："The associated secure drives have been unlocked"。



锁定并解除锁定所有驱动器后、存储阵列中的每个控制器都将重新启动。但是、如果目标存储阵列中已有一些未锁定的驱动器、则控制器不会重新启动。
