---
permalink: um-certificates/use-ca-signed-certificate-um.html 
sidebar: sidebar 
keywords: ca certificate, secure, access, management, system, unified manager 
summary: 您可以获取并导入CA签名的证书、以安全访问托管Unified Manager的管理系统。 
---
= 使用CA签名的证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以获取并导入CA签名的证书、以安全访问托管Unified Manager的管理系统。

.开始之前
* 您必须使用包含安全管理员权限的用户配置文件登录。否则、不会显示证书功能。


.关于此任务
使用CA签名证书是一个两步操作步骤。



== 第1步：完成并提交CSR

您必须先生成证书签名请求(CSR)文件并将其发送到CA。

.开始之前
* 您必须使用包含安全管理员权限的用户配置文件登录。否则、不会显示证书功能。


.关于此任务
此任务介绍如何生成发送给CA的CSR文件、以接收托管Unified Manager和Web服务代理的系统的已签名管理证书。您必须提供有关您的组织的信息以及主机系统的IP地址或DNS名称。

[CAUTION]
====
提交给CA后、请勿生成新的CSR。生成CSR时、系统会创建一个专用密钥对和公有 密钥对。公有 密钥是CSR的一部分、而私钥则保留在密钥库中。当您收到签名证书并将其导入到密钥库中时、系统会确保私钥和公有 密钥都是原始对。因此、在向CA提交新的CSR后、您不能生成新的CSR。否则、控制器将生成新密钥、而从CA收到的证书将不起作用。

====
.步骤
. 选择*证书管理*。
. 从*管理*选项卡中、选择*完成CSR*。
. 输入以下信息、然后单击*下一步*：
+
** *组织*—贵公司或组织的法定全名。包括后缀、例如Inc.或Corp.
** *组织单位(可选)*—组织中负责处理证书的部门。
** *城市/位置*-主机系统或业务所在的城市。
** *省/自治区/直辖市(可选)*—主机系统或业务所在的省/自治区/直辖市。
** *国家/地区ISO代码*—您所在国家/地区的两位数ISO (国际标准化组织)代码、例如美国。


. 输入有关主机系统的以下信息：
+
** *公用名*—安装了Web服务代理的主机系统的IP地址或DNS名称。请确保此地址正确无误；它必须与您在浏览器中输入的地址完全匹配才能访问Unified Manager。请勿包含http：//或https：//。
** *备用IP地址*-如果公用名称为IP地址、则可以选择为主机系统输入任何其他IP地址或别名。对于多个条目、请使用逗号分隔格式。
** *备用DNS名称*-如果公用名称为DNS名称、请输入主机系统的任何其他DNS名称。对于多个条目、请使用逗号分隔格式。如果没有备用DNS名称、但您在第一个字段中输入了DNS名称、请将此名称复制到此处。


. 单击 * 完成 * 。
+
此时、CSR文件将下载到本地系统。下载内容的文件夹位置取决于您的浏览器。

. 将CSR文件提交到CA并请求PEM或DER格式的签名证书。


.完成后
等待CA返回证书文件、然后转到 link:step-3-import-management-certificates-unified.html["第2步：导入管理证书"]。



== 第2步：导入管理证书

收到签名证书后、导入安装了Unified Manager界面的主机系统的证书链。

.开始之前
* 您必须使用包含安全管理员权限的用户配置文件登录。否则、不会显示证书功能。
* 您已生成证书签名请求(.csr文件)并将其发送到CA。
* CA返回了可信证书文件。
* 证书文件安装在本地系统上。
* 如果CA提供了链式证书(例如.p7b文件)、则必须将链式文件解压缩到各个文件中：根证书、一个或多个中间证书以及服务器证书。您可以使用Windows `certmgr`实用程序解压缩文件(右键单击并选择*菜单：所有任务[导出]*)。导出完成后、系统将为链中的每个证书文件显示一个CER"文件。


.步骤
. 选择*证书管理*。
. 从*管理*选项卡中、选择*导入*。
+
此时将打开一个对话框、用于导入证书文件。

. 单击*浏览*以首先选择根文件和中间文件、然后选择服务器证书。
+
文件名将显示在对话框中。

. 单击 * 导入 * 。


.结果
这些文件将上传并进行验证。证书信息将显示在证书管理页面上。
